"""Account, refresh-family, verification, MFA and passkey persistence.

Adapted from open-city-planner 2238e18 (AGPL-3.0-only).
Auth uses its own version table; Registry migration history is unchanged.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0063_auth_persistence"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=True),
        sa.Column("first_name", sa.String(length=120), nullable=False),
        sa.Column("last_name", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=180), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "deactivation_reason",
            sa.Enum("SELF_DEACTIVATED", "ADMIN_DEACTIVATED", name="account_deactivation_reason"),
            nullable=True,
        ),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("email_pending", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferred_language", sa.String(length=16), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "auth_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_auth_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("fk_auth_audit_logs_target_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_audit_logs")),
    )
    op.create_index("idx_auth_audit_logs_actor", "auth_audit_logs", ["actor_user_id"], unique=False)
    op.create_index(
        "idx_auth_audit_logs_created_at", "auth_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "idx_auth_audit_logs_target", "auth_audit_logs", ["target_user_id"], unique=False
    )
    op.create_table(
        "auth_mfa_challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("primary_method", sa.String(length=32), nullable=False),
        sa.Column("redirect_path", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=80), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_mfa_challenges_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_mfa_challenges")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_mfa_challenges_token_hash")),
    )
    op.create_index(
        "idx_auth_mfa_challenges_expires", "auth_mfa_challenges", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_auth_mfa_challenges_user", "auth_mfa_challenges", ["user_id"], unique=False
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_verification_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verification_tokens")),
    )
    op.create_index(
        "idx_email_verification_tokens_hash",
        "email_verification_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        "idx_email_verification_tokens_user_id",
        "email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
    )
    op.create_index(
        "idx_password_reset_tokens_hash", "password_reset_tokens", ["token_hash"], unique=False
    )
    op.create_index(
        "idx_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user_mfa_methods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("setup_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_counter", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_mfa_methods_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_mfa_methods")),
    )
    op.create_index(
        "idx_user_mfa_methods_enabled", "user_mfa_methods", ["user_id", "is_enabled"], unique=False
    )
    op.create_index(
        "uq_user_mfa_methods_totp_user",
        "user_mfa_methods",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("type = 'totp'"),
    )
    op.create_table(
        "user_mfa_recovery_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_mfa_recovery_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_mfa_recovery_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_user_mfa_recovery_codes_code_hash")),
    )
    op.create_index(
        "idx_user_mfa_recovery_codes_user_unused",
        "user_mfa_recovery_codes",
        ["user_id", "used_at"],
        unique=False,
    )
    op.create_table(
        "user_oauth_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=320), nullable=True),
        sa.Column("provider_username", sa.String(length=255), nullable=True),
        sa.Column("provider_avatar_url", sa.Text(), nullable=True),
        sa.Column("provider_profile_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "provider IN ('github', 'google')", name=op.f("ck_user_oauth_accounts_auth_provider")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_oauth_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_oauth_accounts")),
        sa.UniqueConstraint("provider", "provider_subject", name="uq_user_oauth_accounts_identity"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_oauth_accounts_user_provider"),
    )
    op.create_index(
        "idx_user_oauth_accounts_provider", "user_oauth_accounts", ["provider"], unique=False
    )
    op.create_index(
        "idx_user_oauth_accounts_user_id", "user_oauth_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_jti", sa.String(length=64), nullable=True),
        sa.Column("revocation_reason", sa.String(length=80), nullable=True),
        sa.Column("ip_address", sa.String(length=80), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("jti", name=op.f("uq_user_sessions_jti")),
    )
    op.create_index("idx_user_sessions_family_id", "user_sessions", ["family_id"], unique=False)
    op.create_index("idx_user_sessions_jti", "user_sessions", ["jti"], unique=False)
    op.create_index("idx_user_sessions_user_id", "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "user_webauthn_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("aaguid", sa.UUID(), nullable=True),
        sa.Column("transports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("device_type", sa.String(length=32), nullable=True),
        sa.Column("backed_up", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_webauthn_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_webauthn_credentials")),
        sa.UniqueConstraint(
            "credential_id", name=op.f("uq_user_webauthn_credentials_credential_id")
        ),
    )
    op.create_index(
        "idx_user_webauthn_credentials_user", "user_webauthn_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "webauthn_challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("mfa_challenge_id", sa.UUID(), nullable=True),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("challenge", sa.LargeBinary(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=80), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mfa_challenge_id"],
            ["auth_mfa_challenges.id"],
            name=op.f("fk_webauthn_challenges_mfa_challenge_id_auth_mfa_challenges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_webauthn_challenges_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn_challenges")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_webauthn_challenges_token_hash")),
    )
    op.create_index(
        "idx_webauthn_challenges_expires", "webauthn_challenges", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_webauthn_challenges_user", "webauthn_challenges", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # Match Registry migration policy: never silently discard account/security data.
    tables = (
        "users",
        "user_sessions",
        "user_oauth_accounts",
        "email_verification_tokens",
        "password_reset_tokens",
        "user_mfa_methods",
        "user_mfa_recovery_codes",
        "auth_mfa_challenges",
        "user_webauthn_credentials",
        "webauthn_challenges",
        "auth_audit_logs",
    )
    if any(
        op.get_bind().scalar(sa.text(f'SELECT EXISTS (SELECT 1 FROM "{name}")')) for name in tables
    ):
        raise RuntimeError("Cannot discard account/security data; restore compatible service")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_webauthn_challenges_user", table_name="webauthn_challenges")
    op.drop_index("idx_webauthn_challenges_expires", table_name="webauthn_challenges")
    op.drop_table("webauthn_challenges")
    op.drop_index("idx_user_webauthn_credentials_user", table_name="user_webauthn_credentials")
    op.drop_table("user_webauthn_credentials")
    op.drop_index("idx_user_sessions_user_id", table_name="user_sessions")
    op.drop_index("idx_user_sessions_jti", table_name="user_sessions")
    op.drop_index("idx_user_sessions_family_id", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index("idx_user_oauth_accounts_user_id", table_name="user_oauth_accounts")
    op.drop_index("idx_user_oauth_accounts_provider", table_name="user_oauth_accounts")
    op.drop_table("user_oauth_accounts")
    op.drop_index("idx_user_mfa_recovery_codes_user_unused", table_name="user_mfa_recovery_codes")
    op.drop_table("user_mfa_recovery_codes")
    op.drop_index(
        "uq_user_mfa_methods_totp_user",
        table_name="user_mfa_methods",
        postgresql_where=sa.text("type = 'totp'"),
    )
    op.drop_index("idx_user_mfa_methods_enabled", table_name="user_mfa_methods")
    op.drop_table("user_mfa_methods")
    op.drop_index("idx_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.drop_index("idx_password_reset_tokens_hash", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index("idx_email_verification_tokens_user_id", table_name="email_verification_tokens")
    op.drop_index("idx_email_verification_tokens_hash", table_name="email_verification_tokens")
    op.drop_table("email_verification_tokens")
    op.drop_index("idx_auth_mfa_challenges_user", table_name="auth_mfa_challenges")
    op.drop_index("idx_auth_mfa_challenges_expires", table_name="auth_mfa_challenges")
    op.drop_table("auth_mfa_challenges")
    op.drop_index("idx_auth_audit_logs_target", table_name="auth_audit_logs")
    op.drop_index("idx_auth_audit_logs_created_at", table_name="auth_audit_logs")
    op.drop_index("idx_auth_audit_logs_actor", table_name="auth_audit_logs")
    op.drop_table("auth_audit_logs")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    sa.Enum(name="account_deactivation_reason").drop(op.get_bind(), checkfirst=True)
