<script setup lang="ts">
import type { PackageFilters, PublisherSummary } from '~/types/api'
const props = defineProps<{ modelValue: PackageFilters; publishers: PublisherSummary[] }>()
const emit = defineEmits<{ 'update:modelValue': [value: PackageFilters] }>()
function update(key: keyof PackageFilters, value: string) { emit('update:modelValue', { ...props.modelValue, [key]: value, offset: 0 }) }
function clear() { emit('update:modelValue', { q: props.modelValue.q, limit: props.modelValue.limit, offset: 0, sort: props.modelValue.sort || 'relevance' }) }
</script>

<template><aside class="border-t border-slate-200 pt-5 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><div class="flex items-center justify-between"><h2 class="font-bold">Filter</h2><button class="text-sm font-semibold text-link-700" type="button" @click="clear">Clear all</button></div><div class="mt-4 grid gap-4"><label class="grid gap-1 text-xs font-semibold text-slate-600">Publisher<select class="rounded-lg border border-slate-300 bg-white p-2.5 text-sm" :value="modelValue.publisher || ''" @change="update('publisher', ($event.target as HTMLSelectElement).value)"><option value="">Any publisher</option><option v-for="publisher in publishers" :key="publisher.id" :value="publisher.id">{{ publisher.name }}</option></select></label><label class="grid gap-1 text-xs font-semibold text-slate-600">Classification<select class="rounded-lg border border-slate-300 bg-white p-2.5 text-sm" :value="modelValue.classification || ''" @change="update('classification', ($event.target as HTMLSelectElement).value)"><option value="">Any classification</option><option value="first-party">First Party</option><option value="reviewed-community">Reviewed Community</option></select></label><label class="grid gap-1 text-xs font-semibold text-slate-600">Channel<select class="rounded-lg border border-slate-300 bg-white p-2.5 text-sm" :value="modelValue.channel || ''" @change="update('channel', ($event.target as HTMLSelectElement).value)"><option value="">Any channel</option><option value="stable">Stable</option><option value="beta">Beta</option><option value="nightly">Nightly</option></select></label><label class="grid gap-1 text-xs font-semibold text-slate-600">Host version<input class="rounded-lg border border-slate-300 p-2.5 text-sm" :value="modelValue.host || ''" placeholder="e.g. 0.2.0" @change="update('host', ($event.target as HTMLInputElement).value)"></label><label class="grid gap-1 text-xs font-semibold text-slate-600">SDK version<input class="rounded-lg border border-slate-300 p-2.5 text-sm" :value="modelValue.sdk || ''" placeholder="e.g. 1.9.0" @change="update('sdk', ($event.target as HTMLInputElement).value)"></label></div></aside></template>
